name: go_together
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  bot_toast: ^4.0.3
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  animations: ^2.0.7
  syncfusion_flutter_datepicker: ^21.2.8
  flutter_localizations:
    sdk: flutter  
  random_text_reveal: ^0.0.6
  image_picker: ^0.8.7+5
  shared_preferences: ^2.1.2
  provider: ^6.0.5
  toggle_switch: ^2.1.0
  drop_down_list: ^0.0.5
  table_calendar: ^3.0.9
  schedule_widget: ^0.0.3
  logger: ^1.4.0
  syncfusion_flutter_calendar: ^21.2.10
  foldable_list: ^1.0.1
  rounded_expansion_tile: ^0.0.13
  flutter_datetime_picker_plus: ^2.1.0

dependency_overrides:
 intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/.env
    - assets/images/

 