// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3YUkIWjyU6NpVX84MeXve9xIr_1H_mHQ',
    appId: '1:80250456205:web:eca9fd66eedf22143c7ac4',
    messagingSenderId: '80250456205',
    projectId: 'gotogetherforflutter',
    authDomain: 'gotogetherforflutter.firebaseapp.com',
    databaseURL: 'https://gotogetherforflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotogetherforflutter.appspot.com',
    measurementId: 'G-Z3CR73GVXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjyYnbJHXEOYLHuCs7yhn00qv_a3GErts',
    appId: '1:80250456205:android:6eab852cf08f9d003c7ac4',
    messagingSenderId: '80250456205',
    projectId: 'gotogetherforflutter',
    databaseURL: 'https://gotogetherforflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotogetherforflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9pEqWcgdjmvGeV40fMB834Fw3u_4vs0c',
    appId: '1:80250456205:ios:1209545c6998841e3c7ac4',
    messagingSenderId: '80250456205',
    projectId: 'gotogetherforflutter',
    databaseURL: 'https://gotogetherforflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotogetherforflutter.appspot.com',
    iosClientId: '80250456205-2ckl161mlq9ain36masap40depmjsoh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.goTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9pEqWcgdjmvGeV40fMB834Fw3u_4vs0c',
    appId: '1:80250456205:ios:1209545c6998841e3c7ac4',
    messagingSenderId: '80250456205',
    projectId: 'gotogetherforflutter',
    databaseURL: 'https://gotogetherforflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotogetherforflutter.appspot.com',
    iosClientId: '80250456205-2ckl161mlq9ain36masap40depmjsoh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.goTogether',
  );
}
